Notes: Jenkins pipeline
project: ctdc
services:
  backend:
    version: 1.2.2.2
    image: 1.2.2.2
    buildNumber: '2'
  frontend:
    version: 1.2.1.5
    image: 1.2.1.5
    buildNumber: '5'
  files:
    version: 1.1.0.109
    image: 1.1.0.109
    buildNumber: '109'
  authn:
    version: 1.1.0.69
    image: 1.1.0.69
    buildNumber: '69'
